### PR TITLE
Zero percent growth

### PR DESCRIPTION
**Pull request by OrthoDex**
removed the inf label as per @danieldraper 's suggestion.

### CODE REVIEW

**Comment by arunthampi** [comment]
Nice work @OrthoDex 🙌 few things:

- [ ] can you rebase against master?
- [ ] There are some changes in Gemfile.lock (can you please revert those changes?)

Otherwise LGTM to merge

**Comment by OrthoDex** [comment]
Hey @arunthampi , I rebased and reverted the changes to Gemfilel.lock, it updated a few gem versions to the later ones when I ran bundle. Sorry about that :disappointed_relieved:

**Comment by arunthampi** [comment]
@OrthoDex nice thanks! sorry one more change, I think it's better to not show anything instead of showing 0%. In [`bots_helper`](https://github.com/botmetrics/botmetrics/blob/master/app/helpers/bots_helper.rb#L78-L95), if `growth` is nil then it won't show anything so shall we return nil instead of 0.0?

Thanks again for your work 🙏

**Comment by OrthoDex** [comment]
Oh yeah, now that i see that part of the code, it makes sense to not show anything. My bad, i'll fix it in a sec.

**Comment by arunthampi** [comment]
nice thanks! will merge once CI passes

**Comment by OrthoDex** [comment]
Thank you! I am looking to contribute more to this repo, so hopefully I can be of further help :smile:

**Pull request merged**
